### ISSUE TITLE
Merge remaining branches into "TYPO3 Explained" and archive repo

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TyposcriptSyntax#15]

**Comment by sypets** [comment]
* [x] content copied to TYPO3 explained for other branches
* [x] request redirects for bitbucket
* [ ] once redirects are in place, the manual can be taken offline and archived

Status, see Readme: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TyposcriptSyntax/blob/master/README.rst

**Comment by linawolf** [comment]
Repository is archived
