### ISSUE TITLE
Update the conditions used

### ISSUE THREAD

**Issue by Chrissitopher** [TYPO3-Documentation/TYPO3CMS-Reference-TyposcriptSyntax#2]
The document is still using deprecated conditions, e.g. ``[browser=...]`` or ``[system=...]``.

Update it to use conditions, which are *not* deprecated.

**Comment by simonschaufi** [comment]
why don't you just make a pull request?

**Comment by Chrissitopher** [comment]
I just didn't make it til now. It's an issue of time...
